# Config file for air
# Set the working directory
root = "."
tmp_dir = "tmp"

# Watch these file extensions for changes
include_ext = ["go", "tpl", "tmpl", "html"]

# Ignore these directories
exclude_dir = ["assets", "tmp", "vendor"]

[build]
# Build command to generate the binary
cmd = "go build -o ./tmp/main ."

# Path to the binary file to run
bin = "tmp/main"

# Delay in milliseconds before restarting
delay = 1000

# Watch these directories if you specified.
include_dir = []
# Exclude files.
exclude_file = []

# Stop to run old binary when build errors occur.
stop_on_error = true
# This log file places in your tmp_dir.
log = "air_errors.log"

[log]
# Show log time
time = false
level = "info"

# Watcher settings
[watcher]
# Enable watch mode
watch = true

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
